### PR TITLE
Fix the 'more chars after last line' check

### PR DESCRIPTION
**Pull request by Grillo-0**
The current condition expects the last char on the file to be on `end_idx`, but actually it will be at `end_idx - 1`. So, change the allowed difference between `end_idx` and `last_line_ending` from 0 to 1.

### CODE REVIEW

**Comment by syoyo** [comment]
Do you have minimal reproducible .obj file or an unit test for this PR?

**Comment by Grillo-0** [comment]
> Do you have minimal reproducible .obj file or an unit test for this PR?

just added an unit test

**Comment by syoyo** [comment]
The unit test is just check `num_lines`, so I also want to know what issue this PR actually fixes(segmentation fault, parse failure, etc. That's why I wanted minimal reproducible .obj file)

**Comment by Grillo-0** [comment]
> The unit test is just check `num_lines`, so I want to know what issue this PR actually fixes(segmentation fault, parse failure, etc. That's why I wanted minimal reproducible .obj file)

Currently, all files have the line counting wrong, this PR aims to fix that. Any .obj is going to have the line counting wrong.

This happens because the condition that adds +1 to `num_lines` will always return true, because the `end_idx` will never reach `last_line_ending` the maximum value it can reach is `last_line_ending - 1`, as stated in the for loop definition.

But ultimately, this error doesn't seem to cause any problems, at least for now. This was just a nitpick that I found while making #64 :)

**Comment by syoyo** [comment]
> Currently, all files have the line counting wrong, this PR aims to fix that.

Thanks! Understand! And merged!

**Pull request merged**
