### PR TITLE
Add stdio macros

### PR DESCRIPTION
**Pull request by mandyedi**
I added macros for stdio.h (#8).
If you don't mind I used lowercase macros for types like FILE and stderr, but functions remained uppercase.

### CODE REVIEW

**Comment by Marco01809** [comment]
This is a really overengineered solution and I don't see it ever being used since implementing all these functions is impractical.

While #24 may be an okay workaround for the time being, the proper solution is to remove file handling altogether instead of sticking to it and making it more convoluted. fgets is not a particularly well designed function (see the necessary hack #24 to make it work properly) and we'd be better off not using it at all.

Instead we should let the caller specify a callback to request the material file, which will load the file into memory and return a pointer and size to tinyobj. That way the caller could use platform-specific functions like memory mapping.
Instead of using the inconvenient fgets, we can just search for the next newline character to find the end of the line and don't need to allocate memory at all.
This would fix not only #20, but #4 and #8 as well.

**Comment by syoyo** [comment]
> Instead we should let the caller specify a callback to request the material file, which will load the file > into memory and return a pointer and size to tinyobj. That way the caller could use platform-specific > functions like memory mapping.
> Instead of using the inconvenient fgets, we can just search for the next newline character to find the > end of the line and don't need to allocate memory at all.
> This would fix not only #20, but #4 and #8 as well.

Yes, current implementation & design is a bit nasty. It is not recommended to extending it by macro approach.  We are better to redesign & reimplement tinyobj-c by considering:

* Use callback function approach for I/O(and other stuff)
* Read whole data(or mmap it) and find newline characters like this:  https://github.com/syoyo/tinyobjloader/blob/master/experimental/tinyobj_loader_opt.h#L1297

This will give much simpler and cleaner sour code.

**Comment by mandyedi** [comment]
I accidentally closed it, but actually I decided to resolve the issue. As you suggested above I'm going to implement a callback.

**Comment by syoyo** [comment]
> As you suggested above I'm going to implement a callback.

Thanks! :pray:

**Pull request closed without merging**
