### PR TITLE
Fix hash grow

### PR DESCRIPTION
**Pull request by Grillo-0**
If we try to insert an item when the hash table is not completely filled
(i.e. `n` != `capacity`) but the indexes provided by quadratic probing
are all filled, we will end up in an infinite loop. To fix that, always
grow the hash table if we can't insert an item.

After this modification, I've found a null deref, so I added a fix for that too.

### CODE REVIEW

**Comment by syoyo** [comment]
Your comment is the same with https://github.com/syoyo/tinyobjloader-c/pull/65

Please describe about hash glow fix here.

**Comment by Grillo-0** [comment]
> Your comment is the same with #65
> 
> Please describe about hash glow fix here.

Sorry, I sent both at the same time and things got a bit confused XD

**Comment by syoyo** [comment]
Thanks! Confirmed the description. It will help understanding the PR. Let me give some time to figure out the issue of the hash glow logic of existing implementation.

**Comment by Grillo-0** [comment]
> Thanks! Confirmed the description. It will help understanding the PR. Let me give some time to figure out the issue of the hash glow logic of existing implementation.

No problem, if you have any doubts about what I did I'm happy to answer ;)

**Comment by AgentOak** [comment]
And the name of the existing test should be updated to match the removal of `maybe`: https://github.com/syoyo/tinyobjloader-c/blob/3ee1940c9a89f63fca3719b6c7346a61fede865e/test/tinyobj_internal_tests.c#L940

**Comment by Grillo-0** [comment]
> OK, code looks good.
> 
> ```
> If we try to insert an item when the hash table is not completely filled
> (i.e. n != capacity) but the indexes provided by quadratic probing
> are all filled, we will end up in an infinite loop
> ```
> 
> To confirm this PR fixes infinite-loop issue, could you please provide a reproducible infinite-loop test case to here? https://github.com/syoyo/tinyobjloader-c/blob/master/test/tinyobj_regression_tests.c

Ok, so the regression test would fail by never terminating?

**Comment by Grillo-0** [comment]
Ok, just wrote the regression test, but we have a problem.

I can't place the test into [`/test/tinyobj_regression_tests.c`](https://github.com/syoyo/tinyobjloader-c/blob/master/test/tinyobj_regression_tests.c) because the test needs the `hash_table_t` and the `hash_table_*()` functions definitions. And I can't just put `#define TINYOBJ_LOADER_C_IMPLEMENTATION
` on the [`/test/tinyobj_regression_tests.c`](https://github.com/syoyo/tinyobjloader-c/blob/master/test/tinyobj_regression_tests.c) because [`/test/tinyobj_internal_tests.c`](https://github.com/syoyo/tinyobjloader-c/blob/master/test/tinyobj_internal_tests.c) already does that, and we join all the test files into a single executable.

I think of two solutions:
1. Just put the new regression test on [`/test/tinyobj_internal_tests.c`](https://github.com/syoyo/tinyobjloader-c/blob/master/test/tinyobj_internal_tests.c)
2. Separate each test file into its own executable

What you guys think it's the best choice here? (Just for testing I did option 1, but I think that option 2 might be the best one on the long term)

**Comment by syoyo** [comment]
> 2. Separate each test file into its own executable

Yes, we'd like to go with solution 2.(or create dedicated test executable for hash glow. For example create `test/regression/hash_glow_issue64` folder and put test files there).

**Comment by syoyo** [comment]
> Ok, so the regression test would fail by never terminating?

👀 Probably we are better to limit the number of while iteration to avoid infnite-loop in tinyobjloader-c.h like this

```
{
  uint32_t max_iter = 100000;
  uint32_t cnt = 0;
  while (hash_insert(x) != SUCCESS) {
    cnt++;
    if (cnt >= max_iter) {
        fail = true;
        break; // or return error code
    }
   hash_glow(...)
  }
}
```

**Comment by Grillo-0** [comment]
> > Ok, so the regression test would fail by never terminating?
> 
> 👀 Probably we are better to limit the number of while iteration to avoid infnite-loop in tinyobjloader-c.h like this
> 
> ```
> {
>   uint32_t max_iter = 100000;
>   uint32_t cnt = 0;
>   while (hash_insert(x) != SUCCESS) {
>     cnt++;
>     if (cnt >= max_iter) {
>         fail = true;
>         break; // or return error code
>     }
>    hash_glow(...)
>   }
> }
> ```

But this wouldn't be reimplementing part of the logic that solves the bug that the regression test should be testing?

**Comment by Grillo-0** [comment]
> > 2. Separate each test file into its own executable
> 
> Yes, we'd like to go with solution 2.(or create dedicated test executable for hash glow. For example create `test/regression/hash_glow_issue64` folder and put test files there).

done

**Comment by Grillo-0** [comment]
> And the name of the existing test should be updated to match the removal of `maybe`:
> 
> https://github.com/syoyo/tinyobjloader-c/blob/3ee1940c9a89f63fca3719b6c7346a61fede865e/test/tinyobj_internal_tests.c#L940

done

**Comment by syoyo** [comment]
> But this wouldn't be reimplementing part of the logic that solves the bug?

hmm. ok, ignore my idea. 

> so the regression test would fail by never terminating?

Yes, the regression test would fail by never terminating(when the fix was wrong). This is acceptable since we run tests manually and can detect it(by a human). At the moment no CI build & CI tests for tinyobjloader-c

**Comment by syoyo** [comment]
@Grillo-0 So the PR is ready to merge?

**Comment by Grillo-0** [comment]
> @Grillo-0 So the PR is ready to merge?

I just need to add the regression test

**Comment by Grillo-0** [comment]
> @Grillo-0 So the PR is ready to merge?

Just added, now it's ready ;)

**Comment by syoyo** [comment]
@Grillo-0 Thanks! Confirmed unit tests passes, so merged! Thank you for the contribution!

**Pull request merged**
